### ISSUE TITLE
Tried your script, having issues

### ISSUE THREAD

**Issue by eddieatsonic** [dagio/post-jira-comment-with-build-details-step#1]
Can you provide some documentation on what we need to put in the Github message so it knows which Jira ticket to write to? We tried using the same strings as the Github/Jira connectors with no success.

**Comment by dagio** [comment]
The commit message does not matter. It will use the branch name. Here are examples of the 3 valid patterns:
- feature/FOO-123-Add-Something
- hotfix/FOO-123-Add-Something
- FOO-123-Add-Something
