### ISSUE TITLE
Error with build

### ISSUE THREAD

**Issue by nanomb** [dagio/post-jira-comment-with-build-details-step#11]
I tried a commit in master and got the error in branch name.

Then I tried a commit in branch feature/readme and got same error:

     [InvalidArgumentException]                     
      The branch name "feature/readme" is not valid  

shouldn't this branch work correctly?

     if (preg_match('@^(feature|hotfix|bugfix|bug)/([\w]+\-[\d]+)@', $branchName, $groups)) {
            // Ex: feature/PROJECT-123
            return $groups[2];

Thanks in advance!

**Comment by dagio** [comment]
The `feature/readme` does not contains any issue key. A valid name would be `feature/ABC-123-readme` where ABC-123 would be your issue key.

On the latest release (v0.1.12), the step will not fail if the branch name is not correct

**Comment by BirmacherAkos** [comment]
Hi!

We have released a new version [(1.0.0)](https://github.com/bitrise-steplib/steps-post-jira-comment-with-build-details/releases/tag/1.0.0) of [(Dagio’s)](https://github.com/bitrise-community/post-jira-comment-with-build-details-step) Post Jira Comment step.

Changes:

 - It has been rewritten in Golang.
 - Support multiple issue keys.
