### ISSUE TITLE
Dynamic issue comment

### ISSUE THREAD

**Issue by Rusttom** [dagio/post-jira-comment-with-build-details-step#12]
http://joxi.ru/52aylZdFGkbqB2  Hi! $JIRA_ISSUE_KEY what it's means? Where i must put it for working?)

I need, when i start build post a comment with build details for Jira issue (1 build = 1 issue)
I have 1000 difrent build for each issue
For example: for DD-5555 it is Issue i need post to DD-5555 , when build stat automating

**Comment by dagio** [comment]
You don't need to set `JIRA_ISSUE_KEY` unless you want to avoid the step to detect it automatically for you.
If you set the value from a previous step, then it will use it instead of trying to detect it
