### ISSUE TITLE
Support multiple issue keys

### ISSUE THREAD

**Issue by ColtonIdle** [dagio/post-jira-comment-with-build-details-step#14]
The plugin works for me when specifying a single issue key, but most of the time I have multiple. It would be great to be able to specify multiple via a delimiter.

Instead of `XY-123` I should be able to do `XY-123, XY-124, XY-125`

**Comment by BirmacherAkos** [comment]
Hi!

We have released a new version [(1.0.0)](https://github.com/bitrise-steplib/steps-post-jira-comment-with-build-details/releases/tag/1.0.0) of [(Dagio’s)](https://github.com/bitrise-community/post-jira-comment-with-build-details-step) Post Jira Comment step.

Changes:

 - It has been rewritten in Golang.
 - Support multiple issue keys.
