### ISSUE TITLE
Hey dagio - is this an abandoned step?

### ISSUE THREAD

**Issue by viktorbenei** [dagio/post-jira-comment-with-build-details-step#15]
Do you still maintain this step @dagio ? Or if you don't have time to maintain this, should we move this into the Bitrise Community github org?

**Comment by dagio** [comment]
I'm not actively maintaining it anymore.
I recommend to use the JIRA action from Fastlane --> https://docs.fastlane.tools/actions/jira/

**Comment by viktorbenei** [comment]
Got it!

Can you please move the non maintained step repos into: https://github.com/bitrise-community
We'd be happy to take over & maintain them! :)

**Comment by dagio** [comment]
Done. Cheers

**Comment by viktorbenei** [comment]
Thanks @dagio , really we really appreciate it! Just one more question, do you maintain the other three steps you have (https://github.com/dagio?utf8=✓&tab=repositories&q=step&type=source&language=) or should we take over the maintenance of those too?

**Comment by dagio** [comment]
I just transfert them all. Thanks to you !

**Comment by viktorbenei** [comment]
Thank you @dagio ! :)
