### ISSUE TITLE
Additional branch name patterns

### ISSUE THREAD

**Issue by lycha** [dagio/post-jira-comment-with-build-details-step#2]
Hi,
thanks a lot for this Bitrise step! It helps a lot with Jira management. I just wanted to ask if it would be possible to add different branch name patterns like:
- feature/FOO-111
- FOO-111

thanks in advance.

**Comment by dagio** [comment]
Hello @lycha 

The step has been updated and should be merged to Bitrise shortly if everything is ok (PR: https://github.com/bitrise-io/bitrise-steplib/pull/688)

**Comment by dagio** [comment]
Merged
