### ISSUE TITLE
Running in PR mode

### ISSUE THREAD

**Issue by lycha** [dagio/post-jira-comment-with-build-details-step#3]
Thank you very much for quick implementation of branch name patterns. I'm running into one more issue. I would like to add Jira comments for each build  triggered in Pull Request mode but the response is:

```
WARN[13:44:44] The step's (post-jira-comment-with-build-details@0.1.8) Run-If expression evaluated to false - skipping 
INFO[13:44:44] The Run-If expression was: .IsCI | and (not .IsPR) 
```

Would it be possible for you to add this functionality?

best
Kris

**Comment by dagio** [comment]
If you enable it for pull requests you might end up with "duplicate" messages. Are you sure you want to have this ?

**Comment by lycha** [comment]
What do you mean by "duplicate" messages? We have separate workflow for PRs and we need to update information in Jira with current build public instal page. I think it's better to do this once when PR is opened instead of posting every time there is a push to feature branch.

**Comment by dagio** [comment]
Hey @lycha 

I don't have the moment right now but feel free to make a PR.
We should somehow give the choice to run for PR or not to avoid to introduce a BC break.

**Comment by 0xMaty** [comment]
Hey @dagio. I've opened PR with possible solution.

**Comment by dagio** [comment]
Closing for now. @maciejmiarecki @lycha feel free to reopen if you are still looking for that feature
