### ISSUE TITLE
Don't fail the build if the issue key is not found

### ISSUE THREAD

**Issue by paour** [dagio/post-jira-comment-with-build-details-step#5]
Not every build needs an issue key, just skip posting the comment to JIRA if the issue isn't found.

**Comment by paour** [comment]
@dagio do you think this should be an option, or can I change the step to only actually fail if it tried to post to JIRA and couldn't?

**Comment by dagio** [comment]
There a `is_skippable` property that you can set for any steps in your workflow. I think that's what you are looking for ?

More details here : http://devcenter.bitrise.io/tips-and-tricks/dont-mark-build-failed-if-step-fails/

**Comment by paour** [comment]
Indeed, thank you!
