### ISSUE TITLE
More options for issue key detection

### ISSUE THREAD

**Issue by paour** [dagio/post-jira-comment-with-build-details-step#6]
In IssueKeyResolver, could you add more patterns, like:

- `bugfix`, `bug` in addition to `hotfix` and `release` as a prefix
- since the project will usually always be the same for a given workflow, why note make the project token configurable in the step UI, like the Git branch name. I'd like to be able to keep using short branch names such as `bug/id-description` where `id` is the Jira issue number

To make it even more configurable, an upstream step could also provide the JIRA issue key (for example based on the commit message) as an environment variable.

**Comment by paour** [comment]
Another option that would be nice is looking for the issue URL in the commit message…

**Comment by dagio** [comment]
> bugfix, bug in addition to hotfix and release as a prefix

These pattern are already supported

> since the project will usually always be the same for a given workflow, why note make the project token configurable in the step UI, like the Git branch name. I'd like to be able to keep using short branch names such as bug/id-description where id is the Jira issue number

Yes, it should be no problem to add support for the jira issue number only as we already have the project key with the `jira_project` step parameter

> Another option that would be nice is looking for the issue URL in the commit message…

Do you need to tag more than one JIRA issue ?

**Comment by paour** [comment]
Thanks for having merged the PRs.

Ultimately, being able to tag multiple JIRA issues would be nice, but it makes the whole process much more complex, since all environment variables involved need to handle lists of keys. I'm OK with the current system for now.
