### ISSUE TITLE
Build issue: 

### ISSUE THREAD

**Issue by TangentDave** [dagio/post-jira-comment-with-build-details-step#9]
Hi,

Version 0.1.11 is failing with the following error when trying to post to JIRA:
The branch name "Staging" is not valid 
post-jira-comment-with-build-details@0.1.11 (exit code: 1)  

The branch name is correct and the rest of the build succeeds. This being the last step, fails.

**Comment by intari** [comment]
Hi,
Same happens for me 

`
+------------------------------------------------------------------------------+
| (10) post-jira-comment-with-build-details@0.1.11                             |
+------------------------------------------------------------------------------+
| id: post-jira-comment-with-build-details                                     |
| version: 0.1.11                                                              |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2017-04-05T08:07:57-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |

                                         
  [InvalidArgumentException]             
  The branch name "master" is not valid  
                                         

post-message <git-branch> <jira-user> <jira-password> <jira-build-message> <jira-url> `[<jira-project>]`

**Comment by dagio** [comment]
You should not include this step in the workflow associated to master branch. It's appropriate for `feature`, `hotfix`, ... every branches that are related to a particular issue (cf patterns here : https://github.com/dagio/post-jira-comment-with-build-details-step/blob/master/src/IssueKeyResolver.php#L22). I should make it more clear in the documentation

**Comment by dagio** [comment]
You can also bypass the issue key detection by providing an explicit one with the "jira_issue_key" parameter (cf https://github.com/dagio/post-jira-comment-with-build-details-step/blob/master/step.yml#L53). This is just on master at the moment but I will release it soon on the steplib
